{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agno-agentos-starter.frontend-fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "agno-agentos-starter.name" . }}-ui
    helm.sh/chart: {{ include "agno-agentos-starter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "agno-agentos-starter.frontend-fullname" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
  {{- with .Values.frontend.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
