{{- if and (not .Values.existingSecretName) .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agno-agentos-starter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "agno-agentos-starter.name" . }}
    helm.sh/chart: {{ include "agno-agentos-starter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
